version: '3'
services: 
    app: 
        build: ./users/.
        container_name: user-api
        ports:
            - 3333:3333
        volumes: 
            - ./users:/home/node/app

    logs: 
        build: ./logs/.
        container_name: logs-api
        ports:
            - 3334:3333
        volumes: 
            - ./logs:/home/node/app